tap "homebrew/science"
cask_args appdir: "/Applications"

# Install useful stuff
brew "gcc"
brew "cmake"
brew "llvm"
brew "openblas"
brew "pkg-config"
brew "git"
brew "zsh"
brew "python3"
brew "rbenv"
brew "node"
brew "yarn"
brew "r", args: ["with-java", "with-openblas"]
brew "pandoc"
brew "pandoc-citeproc"
brew "gnupg"
brew "gpg-agent"
brew "pinentry-mac"

cask "java"
cask "alfred"
cask "google-chrome"
cask "firefox"
cask "the-unarchiver"
cask "dropbox"
cask "calibre"
cask "spotify"
cask "1password"
cask "things"
cask "flux"
cask "github-desktop"
cask "sublime-text-dev"
cask "visual-studio-code-insiders"
cask "rstudio"
cask "skype"
cask "evernote"
cask "iterm2-beta"
cask "anki"
cask "slack"
cask "hazel"
cask "mactex"
cask "transmission"
cask "vlc"
cask "xquartz"