cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'

# Install useful stuff
brew 'ack'
#brew 'coreutils'
brew 'gcc'
brew 'git'
brew 'zsh'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'r'
brew 'archey'
brew 'node'
brew 'postgresql'
brew 'wget'

cask 'dropbox'
cask 'alfred'
cask 'google-chrome'
cask 'spotify'
cask '1password'
cask 'things'
cask 'flux'
cask 'github-desktop'
cask 'atom'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'skype'
cask 'evernote'
cask 'iterm2'
cask 'hazel'
cask 'little-snitch'
cask 'mactex'
cask 'transmisssion'
cask 'vlc'
cask 'steam'

mas 'twitter', id: 409789998
mas 'Day One', id: 1055511498
