#!/usr/bin/env zsh

# Homebrew
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin"

# Matlab and mlint (not using anymore)
# export PATH="/Applications/MATLAB_R2014b.app/bin:/Applications/MATLAB_R2014b.app/bin/maci64:$PATH"

# MANUAL
export MANPATH="/usr/local/man:$MANPATH"

# Rbenv (https://github.com/sstephenson/rbenv) installed with Homebrew
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# CDPATH
# Add things to make it easy to cd to
export CDPATH=~
export CDPATH=$CDPATH:~/Dropbox/Research
